name: Build BGIKit

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: build exe
        run: msbuild BGIKit.sln /t:clean;rebuild /p:Configuration=Release

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: bgikit-executable
          path: build/Release/*.exe
